### PR TITLE
Fix crash from attempting to access non-existent dependent key in `no-tracked-property-from-args` rule

### LINKED ISSUE #1734: `nodeToDependentKey` error when passing `this.someMethod()`
This error shows up as part of the new rule #1701 

This can be fixed there with some additional checks, but think updating `nodeToDependentKey` to handle missing arguments would be a better idea.

### PR DESCRIPTION
**Pull request by joancc**
Fixes #1734 

1. Open to initial feedback for a better route if this is not desirable. I can add some checks to the no-tracked-properties rule, but figure the current logic should be supported without failing.

```
const hasThisArgsValue =
    node.value &&
    startsWithThisExpression(node.value) &&
    nodeToDependentKey(node.value, context).split('.')[0] === 'args';
```

2. If this path sounds good as a solution, should we be returning the empty string (current) or method name instead?

### CODE REVIEW

File: lib/utils/property-getter.js [hunk 1]
```diff
@@ -83,8 +83,13 @@ function isSimpleThisExpression(node) {
...
   if (types.isCallExpression(nodeWithThisExpression)) {
-    // Looks like: this.get('property')
-    return nodeWithThisExpression.arguments[0].value;
+    if (nodeWithThisExpression.arguments[0]) {
+      // Looks like: this.get('property')
+      return nodeWithThisExpression.arguments[0].value;
+    }
+
+    // Looks like: this.someMethod()
+    return '';
```
Comment (bmish) [inline lib/utils/property-getter.js:92]: Let's use `undefined` to indicate there's no dependent key.

**Review by bmish — COMMENTED** [review]
I think my original goal with `nodeToDependentKey()` was for it to only be called when we knew there would be a dependent key. But since it sounds like it's a hassle for the caller to check for that, your approach of simply bailing out without causing a failure seems reasonable.

**Comment by bmish** [comment]
Since it sounds like this fixes a bug in a rule, can you update the PR title to mention that?

**Comment by joancc** [comment]
Thanks for the feedback. Updated to return undefined and added a check on the original rule `no-tracked-property-from-args`. Wanted to avoid it by returning the empty string, but that's probably misleading.

**Comment by joancc** [comment]
@bmish before merging, want to clone his fix and re-run the rule against a larger codebase. This is the second fix for that rule that I missed and want to avoid a third one. 
Was hoping to get alignment on the fix first, which seems we are in agreement with.

File: lib/rules/no-tracked-properties-from-args.js [hunk 2]
```diff
@@ -16,6 +16,7 @@ function visitClassPropertyOrPropertyDefinition(node, context, trackedImportName
   const hasThisArgsValue =
     node.value &&
     startsWithThisExpression(node.value) &&
+    nodeToDependentKey(node.value, context) &&
     nodeToDependentKey(node.value, context).split('.')[0] === 'args';
```
Comment (bmish) [inline lib/rules/no-tracked-properties-from-args.js:20]: Having to calculate the dependent key twice isn't ideal. Can't we use optional chaining here?

```suggestion
    nodeToDependentKey(node.value, context)?.split('.')[0] === 'args';
```

Comment (joancc) [reply lib/rules/no-tracked-properties-from-args.js]: Fair point!

**Review by bmish — APPROVED** [review]
Thank you!
