### PR TITLE
Fix some crashes including with legacy classes in `no-deprecated-router-transition-methods` and `no-implicit-injections` rules

### LINKED ISSUE #1728: `no-deprecated-router-transition-methods` blows up
```
TypeError: classMembers is not iterable
Occurred while linting /home/boris/project/app/components/some-component.ts:28
Rule: "ember/no-deprecated-router-transition-methods"
    at CallExpression (/home/boris/project/node_modules/eslint-plugin-ember/lib/rules/no-deprecated-router-transition-methods.js:140:37)
    at ruleErrorHandler (/home/boris/project/node_modules/eslint/lib/linter/linter.js:1115:28)
    at /home/boris/project/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/boris/project/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/boris/project/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/home/boris/project/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/home/boris/project/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/home/boris/project/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
    at /home/boris/project/node_modules/eslint/lib/linter/linter.js:1150:32
```

That specific line is the `class` line:
```ts
@classic
@tagName('tr')
class SomeComponent extends Intermediary.extend(SomeMixin) {}
```

### PR DESCRIPTION
**Pull request by rtablada**
When trying the latest version with updated rules, I found there were issues with the two deprecation rules when used with some more obscure legacy Ember object patterns. 

I added tests that would fail on the main branch lib code and updated lib to suit.

Fixes #1728.

### CODE REVIEW

**Comment by rtablada** [comment]
After configuring on another one of our projects I've found some more bugs.

Adding tests and working on them now

File: lib/rules/no-deprecated-router-transition-methods.js [hunk 1]
```diff
@@ -76,26 +76,29 @@ module.exports = {
...
-              serviceInjectImportName
-            ).expression;
-
-            if (serviceExpression.type === 'CallExpression') {
-              if (
-                (serviceExpression.arguments.length === 0 && classMember.key.name === 'router') ||
-                (serviceExpression.arguments.length > 0 &&
-                  serviceExpression.arguments[0].value === 'router')
-              ) {
+        if (serviceInjectImportName) {
```
Comment (rtablada) [inline lib/rules/no-deprecated-router-transition-methods.js:79]: Without this if statement, if inject service wasn't imported: then any property would have been checked/considered as being a service.
