### PR TITLE
Don't suggest nested property brace expansion

### LINKED ISSUE #105: Nested Brace Expanded Properties
I get errors from `ember/use-brace-expansion` with something like this:

```javascript
  sampleProperty: computed(
    'foo.bar.{name,place}',
    'foo.baz.{thing,@each.stuff}',
    'foo.qux.[]',
    function() {
```

It doesn't pass until I nest them all like this:

```javascript
  sampleProperty: computed(
    'foo.{bar.{name,place},baz.{thing,@each.stuff},qux.[]}',
    function() {
```

This does not work. Ember does not support nested brace expansion, per [this comment/code](https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/lib/expand_properties.js#L45).

### PR DESCRIPTION
**Pull request by Kerrick**
Fixes #105

### CODE REVIEW

File: tests/lib/rules/use-brace-expansion.js [hunk 1]
```diff
@@ -16,6 +16,7 @@ eslintTester.run('use-brace-expansion', rule, {
     { code: '{ test: computed(function() {}) }' },
     { code: '{ test: computed("a.test", "b.test", function() {}) }' },
     { code: '{ test: computed("a.{test,test2}", "b", function() {}) }' },
+    { code: '{ test: computed("model.a.{test,test2}", "model.b.{test3,test4}", function() {}) }' },
```
Comment (michalsnik) [inline tests/lib/rules/use-brace-expansion.js]: Please add few more tests with different nesting

File: lib/rules/use-brace-expansion.js [hunk 2]
```diff
@@ -28,15 +28,18 @@ module.exports = {
       CallExpression(node) {
         if (!ember.isComputedProp(node)) return;
 
+        const hasBraces = arr => !!arr.join('.').match(/\{.*\}/g);
```
Comment (michalsnik) [inline lib/rules/use-brace-expansion.js]: I think this function should take a string as a parameter. What do you think?

Comment (Kerrick) [inline lib/rules/use-brace-expansion.js]: I had it like that at first, but then I was forced to do the `join` to each of the arrays inside the `if` predicate. I'm not strongly opinionated either way, but that's why I checked it in it this way.

Should I change it?

File: tests/lib/rules/use-brace-expansion.js (hunk 1 above)
Comment (Kerrick) [inline tests/lib/rules/use-brace-expansion.js]: Good catch -- Adding `{ code: '{ test: computed("foo.bar.{name,place}", "foo.qux.[]", "foo.baz.{thing,@each.stuff}", function() {}) }' },` to `valid` caused a test failure, so my implementation was incomplete.

File: lib/rules/use-brace-expansion.js (hunk 2 above)
Comment (Kerrick) [inline lib/rules/use-brace-expansion.js]: After the refactor I did to fix the failing tests that I added, having `hasBraces` accept the array is definitely more convenience now, since I can pass it directly to `filter`.

**Comment by Kerrick** [comment]
@michalsnik I had to fundamentally change the way I fixed this issue after adding more tests, so I'd greatly appreciate a re-review.

**Comment by Kerrick** [comment]
@michalsnik Great point! I added more tests for that kind of scenario, and re-thought the fix once more.

(I'm not sure why CI failed on node stable, but it passed on node 4 and node 6.)

**Comment by jbandura** [comment]
I'd only suggest adding failing test cases for the `.@each` case, apart from that looks good to me 👍

**Comment by michalsnik** [comment]
@Kerrick I have the same thought as @jbandura. Please add few last failing test cases with `@each` and we're good to 🚀

**Comment by Kerrick** [comment]
Sounds great -- I got caught up at work with a busy spell, but I should be able to get those tests added for you later today or tomorrow.

**Comment by Kerrick** [comment]
Added a failing `@each` test and rebased onto master :+1:
