### PR TITLE
Fix crash with dynamic/variable route name in `no-shadow-route-definition` rule (again)

### LINKED ISSUE #1107: Error while parsing dynamic route map in no-shadow-route-definition rule
Hey everyone! I've faced an issue while upgrading an app to Ember 3.23, which looks like a bug in `eslint-plugin-ember` parser. 

There's a route map that looks similar to this:

```js
const SPORTS = ['footbal', 'baseball', 'basketball'];

Router.map(function() {
  this.route('sports', function () {
    for (let sport of SPORTS) {
      this.route(sport, function () {
      	this.route('info');
        
        if (sport === 'football') {
          this.route('super-bowl'); 
        }
      });
    }
  })
});
```
The real case is more complex, but this example gives an understanding of the structure.

While processing this route map ESLint breaks and throws the following error:
```
TypeError: Cannot read property 'startsWith' of undefined
Occurred while linting /Users/artur/path/to/app/sports/app/router.js:14
    at getRouteBasePath (/Users/artur/path/to/app/sports/node_modules/eslint-plugin-ember/lib/rules/no-shadow-route-definition.js:128:18)
    at getRouteInfo (/Users/artur/path/to/app/sports/node_modules/eslint-plugin-ember/lib/rules/no-shadow-route-definition.js:93:20)
    at CallExpression (/Users/artur/path/to/app/sports/node_modules/eslint-plugin-ember/lib/rules/no-shadow-route-definition.js:60:27)
    at /Users/artur/.config/yarn/global/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/artur/.config/yarn/global/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/artur/.config/yarn/global/node_modules/eslint/lib/linter/node-event-generator.js:256:26)
    at NodeEventGenerator.applySelectors (/Users/artur/.config/yarn/global/node_modules/eslint/lib/linter/node-event-generator.js:285:22)
    at NodeEventGenerator.enterNode (/Users/artur/.config/yarn/global/node_modules/eslint/lib/linter/node-event-generator.js:299:14)
    at CodePathAnalyzer.enterNode (/Users/artur/.config/yarn/global/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:711:23)
```

The error message points to this line:
```js
this.route(sport, function () {
```
and breaks [here](https://github.com/ember-cli/eslint-plugin-ember/blob/master/lib/rules/no-shadow-route-definition.js#L128) because `routePath` is `undefined` (presumably because it's a variable, which isn't defined during static analysis).

It doesn't help to just disable the rule neither in config nor inline – seems like ESLint parses the files eagerly and only takes excludes into account for reporting.

Is it a known issue? I didn't find anything related searching through the issues in this repository.

### PR DESCRIPTION
**Pull request by raido**
Update no-shadow-route-definition rule to work with dynamic route names and paths. This is naive implementation in a sense that we don't validate what is real value of `someVariable` that is used to define route or path. It only relies on the variable name itself and assumes value of `someVariable` might be conflicting.

Closes #1107 

cc @bmish

### CODE REVIEW

File: lib/rules/no-shadow-route-definition.js [hunk 1]
```diff
@@ -12,6 +12,12 @@ function buildErrorMessage(opts) {
   )}`;
 }
 
+function buildUnsupportedArgumentsErrorMessage(routeInfo) {
+  return `Unsupported arguments at ${buildSourceLocationString(
```
Comment (raido) [inline lib/rules/no-shadow-route-definition.js:16]: Instead of crashing hard for other unknown dynamic usages, we log an error instead.

Comment (bmish) [reply lib/rules/no-shadow-route-definition.js:16]: I'd prefer to silently ignore any unexpected arguments / values in route definitions. I don't think it's the job of this rule to validate that the route definitions are formed correctly. The only job of this rule is to looked for shadowed definitions. If something unexpected is encountered, we can just bail out and ignore it.

File: tests/lib/rules/no-shadow-route-definition.js [hunk 2]
```diff
@@ -101,6 +101,10 @@ ruleTester.run('no-shadow-route-definition', rule, {
     // With dynamic/variable route or path name:
     'this.route(someVariable);',
     "this.route('views', { path: someVariable })",
+    `this.route(someVariable, function () {
+      this.route('route');
+    });
+    `,
```
Comment (bmish) [inline tests/lib/rules/no-shadow-route-definition.js:107]: These should be valid test cases:

```
this.route('first', { path: foo });
this.route('second', { path: 'foo' });
```

```
this.route(foo);
this.route('foo');
```

File: lib/rules/no-shadow-route-definition.js [hunk 3]
```diff
@@ -187,3 +195,24 @@ function convertPathToGenericForMatching(sourcePath) {
...
+  return getNodeValue(firstArgument);
+}
+
+function getNodeValue(node) {
+  const isIdentifier = node.type === 'Identifier';
+  const isLiteral = node.type === 'Literal';
+  if (isIdentifier) {
+    return node.name;
+  }
+  if (isLiteral && isString(node.value)) {
```
Comment (bmish) [inline lib/rules/no-shadow-route-definition.js:210]: We have a `types.isStringLiteral` function for this already.

**Review by bmish — CHANGES_REQUESTED** [review]

File: lib/rules/no-shadow-route-definition.js (hunk 1 above)
Comment (raido) [reply lib/rules/no-shadow-route-definition.js:16]: Sure, will remove.

File: tests/lib/rules/no-shadow-route-definition.js (hunk 2 above)
Comment (raido) [reply tests/lib/rules/no-shadow-route-definition.js:107]: Good catch, obviously current implementation does not support it. I will revise, probably something like we have for params and wildcards, normalising variables into translated value.

Comment (raido) [reply tests/lib/rules/no-shadow-route-definition.js:107]: I added cases 🔝  which meant updating implementation quite a bit to detect which type of argument definition we have for path.

I'll rebase once PR is ready for merging, so it is easier to review diff between commits.

File: tests/lib/rules/no-shadow-route-definition.js [hunk 4]
```diff
@@ -101,6 +101,20 @@ ruleTester.run('no-shadow-route-definition', rule, {
...
+    `this.route('first', { path: foo });
+    this.route('second', { path: 'foo' });
+    `,
+    `this.route(foo);
+    this.route('foo');
+    `,
+    'this.route(null)',
+    'this.route(true)',
+    // Test not crashing on unexpected values
+    'this.route({})',
```
Comment (bmish) [inline tests/lib/rules/no-shadow-route-definition.js:118]: Can you add test cases with a function call as the route name / path to make sure we don't crash? Note that I think we should just bail out if we see a function call, we should not try to report linting violations in that situation.

```
this.route(getRouteName());
```

```
this.route('my-route', { path: getRouteName() });
```

Comment (raido) [reply tests/lib/rules/no-shadow-route-definition.js:118]: Will do.

Comment (raido) [reply tests/lib/rules/no-shadow-route-definition.js:120]: Added.

Comment (bmish) [reply tests/lib/rules/no-shadow-route-definition.js:120]: Sorry, one last change, can you actually add a string route nested inside these test cases? Otherwise, we might not be fully exercising the code.

```js
this.route(getRouteName(), function () {
  this.route('route');
});
```

```js
this.route("my-route", { path: getRoutePath() }, function () {
  this.route('route');
});
```

Comment (raido) [reply tests/lib/rules/no-shadow-route-definition.js:124]: You are correct, we did miss few bits. Pushed changes to get those examples passing.

**Review by bmish — APPROVED** [review]
Thank you!

**Comment by raido** [comment]
I would have been cool with rebasing and squashing before merging :) 

Thank you for quick review!

**Comment by bmish** [comment]
Hey @raido, this change hasn't been released yet, but I noticed it is causing a bunch of routes in my application to get incorrectly flagged.

Here's a test case with the issue. Would you be able to fix this? Otherwise I'll need to revert this fix before the next release.

```js
this.route('show', { path: '/:marketingEmailId' });
this.route('edit', { path: '/:marketingEmailId/edit' });
```
