### PR TITLE
use-brace-expansion: Limit lint rule to only trigger for `computed()` but no other macros

### LINKED ISSUE #330: No Brace Expansion incorrectly applies to some computed properties
I linted my code diligently fixing reported errors. Fixing one broke my application since I didn't review it properly.  The snippet was:

```
typeId: computed.or('model.targetTypeId', 'model.typeId'),
```

Which failed for `ember/use-brace-expansion`. I changed it to:

```
typeId: computed.or('model.{targetTypeId,typeId}'),
```

That passed the linting but broke functionality. I don't know if it's possible, but brace expansion should be more context error. Applying the rule in this case broke a function that requires two arguments.

### PR DESCRIPTION
**Pull request by gmurphey**
Fixes #330.

### CODE REVIEW

File: lib/rules/use-brace-expansion.js [hunk 1]
```diff
@@ -27,7 +29,12 @@ module.exports = {
 
     return {
       CallExpression(node) {
-        if (!ember.isComputedProp(node)) return;
+        if (
+          !ember.isComputedProp(node) ||
+          (node.callee.property && ignoredMacros.indexOf(node.callee.property.name) > -1)
+        ) {
+          return;
+        }
```
Comment (Turbo87) [inline lib/rules/use-brace-expansion.js]: is it just `and` and `or` that should not use this? I guess the conservative route here would be to only let it run for `computed(...)` but not for any of the other computed property macros. are there other macros where brace expansion works and makes sense?

Comment (rwjblue) [reply lib/rules/use-brace-expansion.js]: > are there other macros where brace expansion works and makes sense

Probably, but IIRC most of them have "special" / "custom" arguments and would cause similar failure  scenarios to `computed.or` / `computed.and`.

File: lib/rules/use-brace-expansion.js [hunk 2]
```diff
@@ -3,6 +3,8 @@
 const utils = require('../utils/utils');
 const ember = require('../utils/ember');
 
+const ignoredMacros = ['and', 'or'];
```
Comment (rwjblue) [inline lib/rules/use-brace-expansion.js]: Instead of blacklisting `and` and `or`, I think we should only apply to `computed()` itself (aka none of the macros)...

Comment (gmurphey) [reply lib/rules/use-brace-expansion.js]: Should now ignore all computed properties that are member expressions.

**Comment by Turbo87** [comment]
@gmurphey thanks! 👍
