### PR TITLE
Fix false positive in same level routes but nested paths in `no-shadow-route-definition` rule

### LINKED ISSUE #1134: `no-shadow-route-definition` false positive
Hey @raido, your change hasn't been released yet, but I noticed it is causing a bunch of routes in my application to get incorrectly flagged.

Here's a test case with the issue. Would you be able to fix this? Otherwise I'll need to revert this fix before the next release.

```js
this.route('show', { path: '/:marketingEmailId' });
this.route('edit', { path: '/:marketingEmailId/edit' });
```

_Originally posted by @bmish in https://github.com/ember-cli/eslint-plugin-ember/pull/1132#issuecomment-816254737_

### PR DESCRIPTION
**Pull request by raido**
With recent effort (https://github.com/ember-cli/eslint-plugin-ember/pull/1132) to make no-shadow-route-definition rule graceful upon unexpected routes setup, we introduced regression with nested paths via configuration.

This PR fixes introduced regression in PR https://github.com/ember-cli/eslint-plugin-ember/pull/1132.

Closes #1134.

### CODE REVIEW

File: lib/rules/no-shadow-route-definition.js [hunk 1]
```diff
@@ -182,25 +186,30 @@ function getPropertyByKeyName(objectExpression, keyName) {
...
-          return '/*generic-wildcard-for-matching';
-        }
-      }
-      if (routePathInfo.type === SOURCE_PATH_VALUE_TYPE.DYNAMIC) {
-        return `/variable:${mappedValue}`;
-      }
-      return mappedValue;
+      const trimmedValue = routePathInfo.stringValue.trim();
+      const convertedPathForMatchingChunks = trimmedValue
+        .split(URL_CHUNK_SEPARATOR)
```
Comment (raido) [inline lib/rules/no-shadow-route-definition.js:197]: In previous PR for "someVariable" etc. gracefulness, we accidentally removed normalising full paths, this PR brings it back. 🙈

**Comment by bmish** [comment]
I just tested this on my application and it looks like it fixes the false positives, but I still see one net new lint violation:

```js
export default function () {
  this.route('builder', { path: '' }, function () {
    this.route('new', { path: '/campaigns/new' });
    this.route('objective', { path: '/campaigns/:channel/new' });
  });

  this.route('index', { path: '/' }); // new violation: this route is shadowing the `builder` route
}

```

Just want to confirm, is this new violation correct? And can you add a test case for this scenario?

**Comment by raido** [comment]
Check out this twiddle - https://ember-twiddle.com/0819e0289a0da308fbe3295d93e3c2fe?openFiles=router%5C.js%2C - if you comment out route2 in router.js, route 1 will render.

Yes, in your example "index" route is shadowing "builder" route.

**Comment by raido** [comment]
The reason empty strings get picked up as "/" is because we normalize the path value over here - https://github.com/ember-cli/eslint-plugin-ember/blob/65a65ac12a2dc92c50a1ec1e38ad18dbecbb2f5a/lib/rules/no-shadow-route-definition.js#L152

This means our error message will display "/" for the conflicting right side route (the one with empty path) - so this might be bit of confusing if error message vs reality in your router.js do not match.

Probably best would be to show original non normalised path in error message at all times. I'll come back to this tomorrow.

**Comment by bmish** [comment]
Okay, sounds good. And let's be sure to add a test case for this.

**Comment by raido** [comment]
Before going ahead, I looked up how exactly router on Ember side normalises "path".

It seems that any non string value falls-back to "/ + routeName" - https://github.com/emberjs/ember.js/blob/21bd70c773dcc4bfe4883d7943e8a68d203b5bad/packages/%40ember/-internals/routing/lib/system/dsl.ts#L275

From this rule perspective, we kind of support non strings to some extent and I think that's fine but in reality your app would use fallback.

Second decision point is here how to handle empty string and "/" - https://github.com/emberjs/ember.js/blob/21bd70c773dcc4bfe4883d7943e8a68d203b5bad/packages/%40ember/-internals/routing/lib/system/dsl.ts#L152

This confirms current that current implementation for `{path: ""}` is valid once more.

File: lib/rules/no-shadow-route-definition.js [hunk 2]
```diff
@@ -21,7 +22,7 @@ function buildSourceLocationString(routeInfo) {
 }
 
 function buildRouteErrorInfo(routeInfo) {
-  return `"${routeInfo.name}" (${routeInfo.fullPath}, ${buildSourceLocationString(routeInfo)})`;
+  return `"${routeInfo.name}" ("${routeInfo.fullPath}", ${buildSourceLocationString(routeInfo)})`;
```
Comment (raido) [inline lib/rules/no-shadow-route-definition.js:25]: Output is wrapped in double quote marks for empty string paths display. Example: `{ path: ""}`

File: lib/rules/no-shadow-route-definition.js [hunk 3]
```diff
@@ -182,33 +188,37 @@ function getPropertyByKeyName(objectExpression, keyName) {
...
+      return convertedPathForMatchingChunks.join(URL_CHUNK_SEPARATOR);
     })
     .join('');
 }
 
 function convertPathForDisplay(routePathInfos) {
   return routePathInfos
     .map((routePathInfo) => {
-      return routePathInfo.stringValue.trim();
+      return routePathInfo.rawPath;
```
Comment (raido) [inline lib/rules/no-shadow-route-definition.js:221]: For error message we display original path we read from the router.js file for easier mapping which route exactly is conflicting.

File: tests/lib/rules/no-shadow-route-definition.js [hunk 4]
```diff
@@ -144,6 +146,82 @@ ruleTester.run('no-shadow-route-definition', rule, {
...
+              },
+            },
+          }),
+          type: 'CallExpression',
+        },
+      ],
+    },
+    {
+      code: `
+        this.route('post', { path: ' ' });
```
Comment (raido) [inline tests/lib/rules/no-shadow-route-definition.js:189]: Add few cases for paths including whitespace.

File: tests/lib/rules/no-shadow-route-definition.js [hunk 5]
```diff
@@ -499,6 +577,46 @@ ruleTester.run('no-shadow-route-definition', rule, {
         },
       ],
     },
+    {
+      code: `
+        this.route("main", { path: " / " }, function() {
```
Comment (raido) [inline tests/lib/rules/no-shadow-route-definition.js:582]: Another whitespace in paths test case, nested routes this time.

**Comment by raido** [comment]
@bmish ready for review :)

File: tests/lib/rules/no-shadow-route-definition.js [hunk 6]
```diff
@@ -920,7 +1038,7 @@ describe('no-shadow-route-definition', () => {
     });
 
     expect(message).toStrictEqual(
-      'Route "second" (main/, 4L:10C) is shadowing route "first" (main/, 3L:10C)'
+      'Route "second" ("main/", 4L:10C) is shadowing route "first" ("main/", 3L:10C)'
```
Comment (bmish) [inline tests/lib/rules/no-shadow-route-definition.js:1041]: Do we need any other test cases for. the error message generation?

Comment (raido) [reply tests/lib/rules/no-shadow-route-definition.js:1041]: I don't think so, functions generating this output have no decision points - https://github.com/ember-cli/eslint-plugin-ember/blob/8afa9ca42798a04256a451fc13551b1019a26f92/lib/rules/no-shadow-route-definition.js#L13 - so there's is no other path to test.

**Comment by raido** [comment]
I rebased it and not sure why Windows builds failed. 🤷‍♂️

**Comment by raido** [comment]
Code test coverage report says we have 100% coverage - 

`no-shadow-route-definition.js  |     100 |      100 |     100 |     100 | `

🤞 :tada:

**Review by bmish — APPROVED** [review]

**Comment by bmish** [comment]
Thank you!
