### PR TITLE
Fix crash with `no-tracked-properties-from-args` rule

### LINKED ISSUE #1711: `no-tracked-properties-from-args` blows up
```
TypeError: Cannot read properties of null (reading 'object')
Occurred while linting /home/boris/project/app/components/some-component.ts:14
Rule: "ember/no-tracked-properties-from-args"
    at visitClassPropertyOrPropertyDefinition (/home/boris/project/node_modules/eslint-plugin-ember/lib/rules/no-tracked-properties-from-args.js:15:16)
    at PropertyDefinition (/home/boris/project/node_modules/eslint-plugin-ember/lib/rules/no-tracked-properties-from-args.js:58:9)
    at ruleErrorHandler (/home/boris/project/node_modules/eslint/lib/linter/linter.js:1115:28)
    at /home/boris/project/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/boris/project/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/boris/project/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/home/boris/project/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/home/boris/project/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/home/boris/project/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
```

### PR DESCRIPTION
**Pull request by joancc**
Fixes #1711

### CODE REVIEW

File: lib/rules/no-tracked-properties-from-args.js [hunk 1]
```diff
@@ -12,9 +12,9 @@ function visitClassPropertyOrPropertyDefinition(node, context, trackedImportName
     isClassPropertyOrPropertyDefinitionWithDecorator(node, trackedImportName);
 
   const hasThisArgsValue =
-    node.value.object?.type === 'MemberExpression' &&
-    node.value.object?.object.type === 'ThisExpression' &&
-    node.value.object?.property.name === 'args';
+    node.value?.object?.type === 'MemberExpression' &&
```
Comment (bmish) [inline lib/rules/no-tracked-properties-from-args.js:15]: Normally, it's better for us to be checking the type of the nodes we're dealing with, instead of just checking that various properties exist. Can we check the type on `node` and `node.value` before attempting to use them?

Comment (joancc) [reply lib/rules/no-tracked-properties-from-args.js:15]: 👌

**Comment by bmish** [comment]
Looks like you need to rebase on master, lots of extra commits.

File: lib/rules/no-tracked-properties-from-args.js (hunk 1 above)
Comment (joancc) [reply lib/rules/no-tracked-properties-from-args.js]: Some really useful helpers and examples already built-ini I just needed to track down, thanks!

File: lib/rules/no-tracked-properties-from-args.js [hunk 2]
```diff
@@ -12,9 +14,10 @@ function visitClassPropertyOrPropertyDefinition(node, context, trackedImportName
     isClassPropertyOrPropertyDefinitionWithDecorator(node, trackedImportName);
 
   const hasThisArgsValue =
-    node.value.object?.type === 'MemberExpression' &&
-    node.value.object?.object.type === 'ThisExpression' &&
-    node.value.object?.property.name === 'args';
+    node.value &&
+    startsWithThisExpression(node.value) &&
+    nodeToDependentKey(node.value, context) &&
+    nodeToDependentKey(node.value, context).split('.')[0] === 'args';
```
Comment (bmish) [inline lib/rules/no-tracked-properties-from-args.js:20]: Removing unnecessary check:


```suggestion
    node.value &&
    startsWithThisExpression(node.value) &&
    nodeToDependentKey(node.value, context).split('.')[0] === 'args';
```
